workflows:
  ios_unsigned:
    name: iOS Unsigned IPA (shoof_tv)
    instance_type: mac_mini_m1
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: 15.4
      cocoapods: default
      vars:
        APP_NAME: "Shoof TV"
        BUNDLE_ID: "com.shoof.tv"
        IOS_MIN_VERSION: "13.0"

    cache:
      cache_paths:
        - ~/.pub-cache
        - ios/Pods
        - ~/Library/Caches/CocoaPods

    scripts:
      - name: Flutter clean & get
        script: |
          set -e
          flutter --version
          flutter clean
          flutter pub get

      - name: Reinstall CocoaPods
        script: |
          set -e
          cd ios
          rm -rf Pods Podfile.lock
          pod repo update
          pod install --verbose

      - name: Build iOS app (no codesign) & package IPA
        script: |
          set -e
          # يبني .app بدون توقيع
          flutter build ios --release --no-codesign

          APP_PATH="build/ios/iphoneos/Runner.app"
          if [ ! -d "$APP_PATH" ]; then
            echo "Runner.app not found"; exit 1
          fi

          # نحزّم .ipa يدويًا بدون توقيع
          rm -rf Payload Runner-unsigned.ipa
          mkdir -p Payload
          cp -R "$APP_PATH" Payload/
          zip -r -y Runner-unsigned.ipa Payload

    artifacts:
      - Runner-unsigned.ipa
      - build/ios/iphoneos/*.app
