workflows:
  ios_unsigned:
    name: iOS Unsigned IPA (shoof_tv)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: 15.4
      cocoapods: default
      vars:
        APP_NAME: "Shoof TV"
        BUNDLE_ID: "com.shoof.tv"
        IOS_MIN_VERSION: "13.0"

    cache:
      cache_paths:
        - ~/.pub-cache

    scripts:
      - name: Flutter clean & get
        script: |
          flutter --version
          flutter clean
          flutter pub get

      - name: Ensure iOS bundle id & min iOS
        script: |
          # اضبط أقل إصدار iOS في Podfile (لو موجود)
          if [ -f ios/Podfile ]; then
            sed -i '' -E "s/^#?\\s*platform :ios, '.*'/platform :ios, '${IOS_MIN_VERSION}'/" ios/Podfile || true
          fi

          # اضبط المعرف واسم التطبيق في Info.plist
          PLIST="ios/Runner/Info.plist"
          /usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier ${BUNDLE_ID}" "$PLIST"
          /usr/libexec/PlistBuddy -c "Set :CFBundleName ${APP_NAME}" "$PLIST" || \
          /usr/libexec/PlistBuddy -c "Add :CFBundleName string ${APP_NAME}" "$PLIST"
          /usr/libexec/PlistBuddy -c "Set :CFBundleDisplayName ${APP_NAME}" "$PLIST" || \
          /usr/libexec/PlistBuddy -c "Add :CFBundleDisplayName string ${APP_NAME}" "$PLIST"

      - name: Build unsigned IPA (no code sign)
        script: |
          # هذا هو السر: خروج IPA غير موقّع مباشرة بدون طلب فريق توقيع
          flutter build ipa --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/iphoneos/*.app

    triggering:
      events: []   # تشغيل يدوي من لوحة Builds
