workflows:
  ios_unsigned:
    name: iOS Unsigned IPA (shoof_tv)
    instance_type: mac_mini_m1
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: 15.4
      cocoapods: default
      vars:
        APP_NAME: "Shoof TV"
        BUNDLE_ID: "com.shoof.tv"
        IOS_MIN_VERSION: "13.0"

    cache:
      cache_paths:
        - ~/.pub-cache
        - ios/Pods
        - ~/Library/Caches/CocoaPods

    scripts:
      - name: Flutter clean & get
        script: |
          set -e
          flutter --version
          flutter clean
          flutter pub get

      - name: Reinstall CocoaPods
        script: |
          set -e
          cd ios
          rm -rf Pods Podfile.lock
          pod repo update
          pod install --verbose

      - name: Build with xcodebuild (no signing) & package IPA
        script: |
          set -e
          cd ios
          pod install --verbose

          xcodebuild \
            -workspace Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            DEVELOPMENT_TEAM="" \
            PRODUCT_BUNDLE_IDENTIFIER=${BUNDLE_ID} \
            BUILD_DIR="$CM_BUILD_DIR/build_nosign" \
            clean build

          APP_PATH="$CM_BUILD_DIR/build_nosign/Release-iphoneos/Runner.app"
          if [ ! -d "$APP_PATH" ]; then
            echo "Runner.app not found at $APP_PATH"
            APP_PATH=$(find ~/Library/Developer/Xcode/DerivedData -type d -name "Runner.app" | head -n 1 || true)
          fi
          if [ ! -d "$APP_PATH" ]; then
            echo "Runner.app not found after build"
            exit 1
          fi

          cd "$CM_BUILD_DIR"
          rm -rf Payload Runner-unsigned.ipa
          mkdir Payload
          cp -R "$APP_PATH" Payload/
          zip -r -y Runner-unsigned.ipa Payload

          echo "Built IPA at: $CM_BUILD_DIR/Runner-unsigned.ipa"
          ls -lh "$CM_BUILD_DIR" || true

    artifacts:
      - Runner-unsigned.ipa
      - build_nosign/Release-iphoneos/*.app
