workflows:
  ios_unsigned:
    name: iOS Unsigned IPA (shoof_tv)
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      flutter: stable
      xcode: 15.4
      cocoapods: default
      vars:
        APP_NAME: "Shoof TV"
        BUNDLE_ID: "com.shoof.tv"
        IOS_MIN_VERSION: "13.0"

    cache:
      cache_paths:
        - ~/.pub-cache
        - ios/Pods
        - ~/Library/Caches/CocoaPods

    scripts:
      - name: Flutter clean & get
        script: |
          set -e
          flutter --version
          flutter clean
          flutter pub get

      - name: Reinstall CocoaPods
        script: |
          set -e
          cd ios
          rm -rf Pods Podfile.lock
          pod repo update
          pod install --verbose
          


      - name: Print Pods tree
        script: |
          set -e
          cd ios
          pod --version
          pod deintegrate
          pod install --repo-update
          xcodebuild -workspace Runner.xcworkspace -scheme Runner -showBuildSettings | grep -E "HEADER|FRAMEWORK|PODS_ROOT" || true


      - name: Build iOS IPA (unsigned)
        script: |
          set -e
          flutter build ipa --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
