# codemagic.yaml  ← يجب أن يكون في جذر المستودع (root)

workflows:
  ios_unsigned:
    name: iOS Unsigned IPA (shoof_tv)
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: 15.4
      cocoapods: default
      vars:
        APP_NAME: "Shoof TV"
        BUNDLE_ID: "com.shoof.tv"

    cache:
      cache_paths:
        - ~/.pub-cache
        - ios/Pods
        - ~/Library/Caches/CocoaPods

    scripts:
      - name: Flutter clean & get
        script: |
          set -e
          flutter --version
          flutter clean
          flutter pub get
          flutter precache --ios

      - name: Ensure Info.plist & Podfile (force iOS 13 / disable bitcode)
        script: |
          set -e
          PLIST="ios/Runner/Info.plist"
          /usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier ${BUNDLE_ID}" "$PLIST"
          /usr/libexec/PlistBuddy -c "Set :CFBundleName ${APP_NAME}" "$PLIST" || \
          /usr/libexec/PlistBuddy -c "Add :CFBundleName string ${APP_NAME}" "$PLIST"
          /usr/libexec/PlistBuddy -c "Set :CFBundleDisplayName ${APP_NAME}" "$PLIST" || \
          /usr/libexec/PlistBuddy -c "Add :CFBundleDisplayName string ${APP_NAME}" "$PLIST"

          # Podfile نظيف مع iOS 13 وإيقاف Bitcode
          cat > ios/Podfile <<'EOF'
          platform :ios, '13.0'
          ENV['COCOAPODS_DISABLE_STATS'] = 'true'

          def flutter_root
            generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
            unless File.exist?(generated_xcode_build_settings_path)
              raise "Generated.xcconfig must exist. Run 'flutter pub get' and try again."
            end
            File.foreach(generated_xcode_build_settings_path) do |line|
              matches = line.match(/FLUTTER_ROOT\=(.*)/)
              return matches[1].strip if matches
            end
            raise "FLUTTER_ROOT not found."
          end

          require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)
          flutter_ios_podfile_setup

          target 'Runner' do
            # ربط ثابت لتقليل مشاكل بعض الحزم
            use_frameworks! :linkage => :static
            use_modular_headers!
            flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
          end

          post_install do |installer|
            # عطّل BITCODE وثبّت iOS 13 لكل الـ Pods
            installer.pods_project.targets.each do |t|
              flutter_additional_ios_build_settings(t)
              t.build_configurations.each do |config|
                config.build_settings['ENABLE_BITCODE'] = 'NO'
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
              end
            end
            # عطّل BITCODE أيضاً على أهداف Runner
            installer.aggregate_targets.each do |aggregate_target|
              aggregate_target.user_targets.each do |user_target|
                user_target.build_configurations.each do |config|
                  config.build_settings['ENABLE_BITCODE'] = 'NO'
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
                end
              end
            end
          end
          EOF

      - name: Pod install (fresh)
        script: |
          set -e
          cd ios
          rm -rf Pods Podfile.lock
          pod repo update
          pod install --verbose
          cd ..

      # بناء IPA عبر Flutter (بدون توقيع)
      - name: Flutter build ipa (no code sign)
        script: |
          set -e
          flutter build ipa --release --no-codesign
          ls -lah build/ios/ipa

      # تحقق من وجود flutter_assets داخل IPA ثم صدّره كأثر بناء
      - name: Verify & export unsigned IPA
        script: |
          set -e
          IPA="build/ios/ipa/Runner.ipa"
          if [ ! -f "$IPA" ]; then
            echo "❌ Runner.ipa not found at $IPA"
            ls -R build || true
            exit 1
          fi
          unzip -l "$IPA" | grep -q "App.framework/flutter_assets/AssetManifest.bin" \
            || { echo "❌ flutter_assets missing inside IPA"; exit 1; }
          cp "$IPA" "$CM_ARTIFACTS/shoof_tv-unsigned.ipa"
          echo "✅ Created $CM_ARTIFACTS/shoof_tv-unsigned.ipa"

    artifacts:
      - $CM_ARTIFACTS/shoof_tv-unsigned.ipa

    triggering:
      events: []   # تشغيل يدوي من لوحة Codemagic
